### ISSUE TITLE
Error: (401) Unauthorized

### ISSUE THREAD

**Issue by f1rstsurf** [sudheer-ranga/aliexpress-product-scraper#10]
Hi, 

i'm currently facing an issue due an outdated dependencie (agent-base) :

```
HTTPError: Response code 401 (Unauthorized)
    at Request.<anonymous> (/home/adrien/Documents/dropshapp/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1600086737470,
    socket: 1600086737474,
    lookup: 1600086737737,
    connect: 1600086737745,
    secureConnect: 1600086737764,
    upload: 1600086737765,
    response: 1600086738120,
    end: 1600086738133,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 4,
      dns: 263,
      tcp: 8,
      tls: 19,
      request: 1,
      firstByte: 355,
      download: 13,
      total: 663
    }
  }
}
```

According to agent-base, the error has been fixed in version >= 5, could you please update your dependencies ?

```
(node:6408) [DEP0139] DeprecationWarning: Calling process.umask() with no arguments is prone to race conditions and is a potential security vulnerability.
└─┬ aliexpress-product-scraper@1.0.5
  └─┬ puppeteer@1.20.0
    └─┬ https-proxy-agent@2.2.4
      └── agent-base@4.3.0
```

**Comment by sudheer-ranga** [comment]
Please update to latest version v2.0.2. All issues are fixed.
