### ISSUE TITLE
Execution error: runParams is not defined

### ISSUE THREAD

**Issue by iicc1** [sudheer-ranga/aliexpress-product-scraper#2]
Hello, I'm trying to run the sample code, with the npm package installed and downloading this repo, and I get the following error: "runParams is not defined".

The problem seems to be in this line: https://github.com/sudheer-ranga/aliexpress-product-scraper/blob/master/src/aliexpressProductScraper.js#L14

Any idea? Thanks in advance

Full log:
`(node:32828) UnhandledPromiseRejectionWarning: Error: Evaluation failed: ReferenceError: runParams is not defined
    at __puppeteer_evaluation_script__:1:8
    at ExecutionContext._evaluateInternal (C:\Users\iicc\Desktop\xxxx\xxxx\node_modules\puppeteer\lib\ExecutionContext.js:122:13)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at ExecutionContext.<anonymous> (C:\Users\iicc\Desktop\xxxx\xxxx\node_modules\puppeteer\lib\helper.js:111:15)
    at DOMWorld.evaluate (C:\Users\iicc\Desktop\xxxx\xxxx\node_modules\puppeteer\lib\DOMWorld.js:112:20)
    at process._tickCallback (internal/process/next_tick.js:68:7)
  -- ASYNC --
    at Frame.<anonymous> (C:\Users\iicc\Desktop\xxxx\xxxx\node_modules\puppeteer\lib\helper.js:111:15)
    at Page.evaluate (C:\Users\iicc\Desktop\xxxx\xxxx\node_modules\puppeteer\lib\Page.js:833:43)
    at Page.<anonymous> (C:\Users\iicc\Desktop\xxxx\xxxx\node_modules\puppeteer\lib\helper.js:112:23)
    at AliexpressProductScraper (C:\Users\iicc\Desktop\xxxx\xxxx\node_modules\aliexpress-product-scraper\src\aliexpressProductScraper.js:14:37)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:32828) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:32828) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. `

**Comment by Ryanb58** [comment]
2nd this.

**Comment by sudheer-ranga** [comment]
Sorry about the issue. This was fixed long back, but the npm package was not updated. I have pushed a new package to npm. `v1.0.5`. Let me know if it solves your issue.

**Comment by tzdigital** [comment]
Hi,
where does this "runParams" come from I see it nowhere ?
I have the same error as iicc1

thx
